version: 2.0
jobs:
  build:
    docker:
      - image: arm64v8/debian:latest
        environment:
          - ENV: CI
    working_directory: ~/
    steps:
     - run: |
         apt-get -qq update
         apt install -y git binutils-dev genisoimage liblzma-dev syslinux
     - checkout
     - run: |
         git clone https://github.com/ipxe/ipxe.git ipxe
         cd ipxe
         make bin-arm64-efi/snp.efi
